#8004 表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  #服务别名----注册zookeeper到注册中心
  cloud:
    zookeeper:
      connect-string: zookeeper.com:2181
